Lead generation recipe V0 [DRAFT - DO NOT REVIEW]
airtop-ai/examples-python pull request #9
Opened 2024-12-10 02:50 UTC by educr6

2024-12-19 22:36 UTC, nrotstan requested changes
Thanks for working through all this, Eduardo!

Since this is a recipe and we want it to be as easy to read and understand as possible, I think we should include the prompt and schema (and relevant pydantic classes if any) with each node file, rather than having all of them in a separate prompts.py file. The current organizational approach requires the developer to do a lot of bouncing around between different files in the project to understand what each piece is doing.

Also, I personally would like to see a little more detail in the documentation explaining the purpose of each piece and how it fits together with everything else. Some pieces are well documented. But, for example, the enrichment node just says `Enrich the therapist information with additional data.` which doesn't really provide much detail about what it actually is doing, and so the developer is forced to figure it out on their own. I think many of the nodes are like that.

2024-12-19 22:40 UTC, nrotstan commented on examples/lead-generation/.env.example
> +LANGCHAIN_API_KEY="langchain_api_key"
Is this just for langsmith?

2024-12-19 22:41 UTC, nrotstan commented on examples/lead-generation/Pipfile
> +[[source]]
I think we've decided to standardize on using Poetry for Python package management.

2024-12-19 22:43 UTC, nrotstan commented on examples/lead-generation/airtop_client.py
> +class AirtopClient:
Is there a reason for creating your own AirtopClient wrapper with your own methods for creating sessions and windows? It feels a little odd in a recipe showing off our SDK, like maybe our SDK is missing some pieces. If it is, that's probably worth discussing.

2025-03-24 22:12 UTC, closed without merging

2025-03-24 22:12 UTC, aidylka commented
@educr6 , I think this is a stale PR that can be closed. I'm closing it but reopen it if you still need it.